### ISSUE TITLE
Compile fails on Rust 1.38 and 1.39

### ISSUE THREAD

**Issue by taiki-e** [BurntSushi/termcolor#35]
`cfg(doctest)` implemented in Rust 1.38 as an unstable feature, and stabilized in Rust 1.40. It compiles fine on Rust 1.37 and older, but fails on Rust 1.38 and 1.39, where this feature existed as an unstable feature.

https://github.com/BurntSushi/termcolor/blob/b052b61ba052c7e5672bb91516982d27cbf9129d/src/lib.rs#L122-L125

Error:
```console
$ cargo +1.39.0 check
    Checking termcolor v1.1.1 (/Users/taiki/projects/termcolor)
error[E0658]: `cfg(doctest)` is experimental and subject to change
   --> src/lib.rs:122:7
    |
122 | #[cfg(doctest)]
    |       ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/62210
```

cc https://github.com/BurntSushi/termcolor/pull/31
Related: https://github.com/rust-lang/regex/issues/685

**Comment by taiki-e** [comment]
Filed #36 to fix this.
