### PR TITLE
tests: remove use of doc_comment crate

### LINKED ISSUE #35: Compile fails on Rust 1.38 and 1.39
`cfg(doctest)` implemented in Rust 1.38 as an unstable feature, and stabilized in Rust 1.40. It compiles fine on Rust 1.37 and older, but fails on Rust 1.38 and 1.39, where this feature existed as an unstable feature.

https://github.com/BurntSushi/termcolor/blob/b052b61ba052c7e5672bb91516982d27cbf9129d/src/lib.rs#L122-L125

Error:
```console
$ cargo +1.39.0 check
    Checking termcolor v1.1.1 (/Users/taiki/projects/termcolor)
error[E0658]: `cfg(doctest)` is experimental and subject to change
   --> src/lib.rs:122:7
    |
122 | #[cfg(doctest)]
    |       ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/62210
```

cc https://github.com/BurntSushi/termcolor/pull/31
Related: https://github.com/rust-lang/regex/issues/685

### PR DESCRIPTION
**Pull request by taiki-e**
Removes the use of doc_comment for now.

Fixes #35

### CODE REVIEW

**Review by BurntSushi — APPROVED** [review]
Thanks!

**Comment by BurntSushi** [comment]
This PR is on crates.io in `termcolor 1.1.2`.
